#!/usr/bin/env bash

if [ ! -f "${HOME}/.fvttmgr.cfg" ]; then
  echo "ERROR: ${HOME}/.fvttmgr.cfg not found!"
  exit 1
fi

. ${HOME}/.fvttmgr.cfg

if [ "${HOST}" == "" ]; then
  echo "ERROR: HOST not set!"
  exit 1
fi

if [ "${BACKUP_DIR}" == "" ]; then
  echo "ERROR: BACKUP_DIR not set!"
  exit 1
fi

if [ ! -d "${BACKUP_DIR}" ]; then
  echo "ERROR: ${BACKUP_DIR} not found!"
  exit 1
fi

GAME=""
if [ "$1" != "" ]; then
    GAME="$1"
fi

ssh ${HOST} "docker stop ${GAME} 2> /dev/null"

set -e

ssh $HOST "ls foundryvtt-${GAME} 2> /dev/null"
if [ "$?" != "0" ]; then
    echo "Game foundryvtt-${GAME} does not exist"
    exit 1
fi

echo "Creating archive..."
ssh $HOST "zip -r foundryvtt-${GAME}.zip foundryvtt-${GAME}"

echo "Copying archive..."
scp $HOST:~/foundryvtt-${GAME}.zip ${BACKUP_DIR}

echo "Done!"
